version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000"]

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: very-secret-password7849357893487953
      MYSQL_DATABASE: hive
    ports: 
      - "33006:3306"
    networks:
      - app-network
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql

  hive-ai:
    build:
      context: ./itvb23ows-hive-ai
      dockerfile: Dockerfile
    ports: 
      - "5000:5000"
    networks:
      - app-network
    command: ['flask', '--app', 'app', 'run', '-h', '0.0.0.0', '--debug']
    
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile_jenkins
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - sonarqube
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: 'true'
      
  sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      ports:
        - "9000:9000"
      networks:
        - app-network

networks:
  app-network:
    