version: '3'

services:
  php-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql-db
    networks:
      - app-network
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000"]

  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: very-secret-password
      MYSQL_DATABASE: hive
    ports: 
      - "33006:3306"
    networks:
      - app-network
    volumes:
      - ./hive.sql:/docker-entrypoint-initdb.d/hive.sql
    
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - sonarqube

  sonarqube:
      image: sonarqube:latest
      container_name: sonarqube
      ports:
        - "9000:9000"
      networks:
        - app-network

networks:
  app-network:
    