FROM jenkins/jenkins:lts

USER root
RUN apt-get update && apt-get install -y curl bash

RUN curl -fsSL https://get.docker.com | sh

RUN curl -L https://github.com/docker/compose/releases/download/v2.23.3/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose \
    && chmod +x /usr/local/bin/docker-compose

RUN docker-compose --version